package Vista;

import Persistencia.ArchivoTexto;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.*;
import java.io.BufferedReader;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import java.util.Formatter;
import java.util.Properties;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Lenovo
 */
public class Formulario extends javax.swing.JFrame {
    String barra = File.separator;
    String Ubicacion = System.getProperty("user.dir") + "Registros" + barra;
    
    
    public Formulario() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        JOptionPane.showMessageDialog(null, "TUTORIAL\nEn el apartado de codigo puede introducir el dato de codigo.\nPero tambien sirve para Editar casos mediante el codigo y eliminar, esto se hace introduciendo el codigo en el apartado de codigo y le da a editar o eliminar.\nPara Registrar simplemente tienes que indroducir toda la informacion y le da al boton registrar.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        DatoCodigo = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DatoDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DatoCausaInvestigacion = new javax.swing.JTextField();
        DatoCodigoPrio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DatoNombreClave = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DatoTipoCaso = new javax.swing.JTextField();
        jButtonRegistarse = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelTitulo.setText("Formulario de caso");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 240, 35));

        DatoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatoCodigoActionPerformed(evt);
            }
        });
        DatoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DatoCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(DatoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 140, 27));

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodigo.setText("Codigo");
        getContentPane().add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Descripcion del caso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 151, -1, -1));

        DatoDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatoDescripcionActionPerformed(evt);
            }
        });
        DatoDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DatoDescripcionKeyTyped(evt);
            }
        });
        getContentPane().add(DatoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 143, 52));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Causa de investigacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 223, -1, -1));

        DatoCausaInvestigacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DatoCausaInvestigacionKeyTyped(evt);
            }
        });
        getContentPane().add(DatoCausaInvestigacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 143, 27));

        DatoCodigoPrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatoCodigoPrioActionPerformed(evt);
            }
        });
        DatoCodigoPrio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DatoCodigoPrioKeyTyped(evt);
            }
        });
        getContentPane().add(DatoCodigoPrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 143, 27));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Codigo de Prioridad ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre Clave");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        DatoNombreClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DatoNombreClaveKeyTyped(evt);
            }
        });
        getContentPane().add(DatoNombreClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 143, 27));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tipo de Caso");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        DatoTipoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatoTipoCasoActionPerformed(evt);
            }
        });
        DatoTipoCaso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DatoTipoCasoKeyTyped(evt);
            }
        });
        getContentPane().add(DatoTipoCaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 143, 27));

        jButtonRegistarse.setBackground(new java.awt.Color(248, 6, 204));
        jButtonRegistarse.setText("Registrarse");
        jButtonRegistarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jButtonEditar.setBackground(new java.awt.Color(248, 6, 204));
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jButtonEliminar.setBackground(new java.awt.Color(248, 6, 204));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        jButtonLimpiar.setBackground(new java.awt.Color(248, 6, 204));
        jButtonLimpiar.setText("Limpiar pantalla");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(153, 0, 153));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Casos2Modi\\src\\Imagen Proyecto\\ubuntu-linux-minimalism_3840x2160_xtrafondos.com.jpg")); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatoDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatoDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatoDescripcionActionPerformed

    private void DatoCodigoPrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatoCodigoPrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatoCodigoPrioActionPerformed

    private void DatoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatoCodigoActionPerformed
        
    }//GEN-LAST:event_DatoCodigoActionPerformed

    private void jButtonRegistarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarseActionPerformed
        crear();
    
    }//GEN-LAST:event_jButtonRegistarseActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        Editar();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        Eliminar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        DatoCodigo.setText("");
        DatoDescripcion.setText("");
        DatoCausaInvestigacion.setText("");
        DatoCodigoPrio.setText("");
        DatoNombreClave.setText("");
        DatoTipoCaso.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void DatoCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatoCodigoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
         if (!numeros){
            JOptionPane.showMessageDialog(null, "ERROR \nTIENE QUE INTRODUCIR NUMEROS");
            evt.consume();
        }
        if (DatoCodigo.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_DatoCodigoKeyTyped

    private void DatoDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatoDescripcionKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "ERROR \nTIENE QUE INTRODUCIR LETRAS");
            evt.consume();
        }
    }//GEN-LAST:event_DatoDescripcionKeyTyped

    private void DatoCausaInvestigacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatoCausaInvestigacionKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "ERROR \nTIENE QUE INTRODUCIR LETRAS");
            evt.consume();
        }
    }//GEN-LAST:event_DatoCausaInvestigacionKeyTyped

    private void DatoCodigoPrioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatoCodigoPrioKeyTyped
        JOptionPane.showMessageDialog(null, "Tiene que introducir un caracter de entre A, B y C\nEquivalen (A = poca importancia, B = moderada, C = relevante)");
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "ERROR \nTIENE QUE INTRODUCIR LETRAS");
            evt.consume();
        }
       
    }//GEN-LAST:event_DatoCodigoPrioKeyTyped

    private void DatoNombreClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatoNombreClaveKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "ERROR \nTIENE QUE INTRODUCIR LETRAS");
            evt.consume();
        }
    }//GEN-LAST:event_DatoNombreClaveKeyTyped

    private void DatoTipoCasoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatoTipoCasoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "ERROR \nTIENE QUE INTRODUCIR LETRAS");
            evt.consume();
        }
        if (DatoTipoCaso.getText().equals("Homicidio")) {
            JOptionPane.showMessageDialog(null, "Se registra adicionalmente un segundo detective, que es el encargado de realizar tareas secundarias como interrogatorios, análisis de pruebas, etc.");
        }
        if (DatoTipoCaso.getText().equals("Narcotico")) {
            JOptionPane.showMessageDialog(null, "se registra adicionalmente si es un caso local, estatal o federal");
        }
        if (DatoTipoCaso.getText().equals("Cibercrimen")) {
            JOptionPane.showMessageDialog(null, "Se adiciona la línea de cibercrimen asociada robo de identidad, robo de información, fraudes por internet, etc.");
        }
        if (DatoTipoCaso.getText().equals("homicidio")) {
            JOptionPane.showMessageDialog(null, "Se registra adicionalmente un segundo detective, que es el encargado de realizar tareas secundarias como interrogatorios, análisis de pruebas, etc.");
        }
        if (DatoTipoCaso.getText().equals("narcotico")) {
            JOptionPane.showMessageDialog(null, "se registra adicionalmente si es un caso local, estatal o federal");
        }
        if (DatoTipoCaso.getText().equals("cibercrimen")) {
            JOptionPane.showMessageDialog(null, "Se adiciona la línea de cibercrimen asociada robo de identidad, robo de información, fraudes por internet, etc.");
        }
    }//GEN-LAST:event_DatoTipoCasoKeyTyped

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void DatoTipoCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatoTipoCasoActionPerformed
        
    }//GEN-LAST:event_DatoTipoCasoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DatoCausaInvestigacion;
    private javax.swing.JTextField DatoCodigo;
    private javax.swing.JTextField DatoCodigoPrio;
    private javax.swing.JTextField DatoDescripcion;
    private javax.swing.JTextField DatoNombreClave;
    private javax.swing.JTextField DatoTipoCaso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonRegistarse;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void crear() {

        String archivo = DatoCodigo.getText() + ".txt";
        File CrearUbi = new File(Ubicacion);
        File crearArchivo = new File(Ubicacion + archivo);
        if (DatoCodigo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor Ingrese el codigo del caso que desea buscar");
        }else{
            try {
                if (crearArchivo.exists()) {
                    JOptionPane.showMessageDialog(null,"El Caso ya se encuentra registrado");
                }else{
                    CrearUbi.mkdirs();
                    Formatter CrearFormatter = new Formatter(Ubicacion+archivo);
                    CrearFormatter.format("%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n"
                            
                            ,"Codigo: " +DatoCodigo.getText()
                            ,"Descripcion del Caso: " + DatoDescripcion.getText()
                            ,"Causa de Investigacion: " + DatoCausaInvestigacion.getText()
                            ,"Codigo de prioridad: " + DatoCodigoPrio.getText()
                            ,"Nombre clave: " + DatoNombreClave.getText()
                            ,"Tipo de caso: " + DatoTipoCaso.getText());
                    CrearFormatter.close();
                    JOptionPane.showMessageDialog(null, "Registro Exitoso");

                }      
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Registro Incorrecto");
            }
        }   
    }
 

    private void Editar() {
        File direccion = new File (Ubicacion+DatoCodigo.getText()+".txt");
        if (DatoCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por Favor ingrese el codigo del caso que desea editar\n En el  apartado de codigo");
        } else {
            if (direccion.exists()) {
                try {
               FileWriter escribir = new FileWriter(Ubicacion+DatoCodigo.getText()+".txt");
               
               String Codigo = "Codigo: ";
               String DecripcionCaso = "Descripcion del Caso: ";
               String CausaInvestigacion = "Causa de Investigacion: ";
               String CodigoPrioridad = "Codigo de prioridad: ";
               String NombreClave = "Nombre clave: ";
               String TipoCaso = "Tipo de caso: ";
                    PrintWriter guardado = new PrintWriter(escribir);
                    guardado.println(Codigo + DatoCodigo.getText());
                    guardado.println(DecripcionCaso + DatoDescripcion.getText());
                    guardado.println(CausaInvestigacion + DatoCausaInvestigacion.getText());
                    guardado.println(CodigoPrioridad + DatoCodigoPrio.getText());
                    guardado.println(NombreClave + DatoNombreClave.getText());
                    guardado.println(TipoCaso + DatoTipoCaso.getText());
                    escribir.close();
                    JOptionPane.showMessageDialog(null, "Registro del caso editado correctamente.");
               
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error "+ e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El codigo del caso no se encuentra registrado.");
            }
        }
    }

    private void Eliminar() {
        
        File direccion = new File (Ubicacion+DatoCodigo.getText()+".txt");
        String botones[] = {"Eliminar", "Cancelar"};
        
        if (DatoCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un codigo de caso\n En el  apartado de codigo");
        } else {
            if (direccion.exists()) {
                try {
                    FileInputStream CerrarArchivo = new FileInputStream(direccion);
                    CerrarArchivo.close();
                    int opc = JOptionPane.showOptionDialog(null, "¿Estas seguro que desea eliminar del registro a: ?" + DatoCodigo.getText(), "Eliminacion",0,0,null,botones,null);
                    if (opc == JOptionPane.YES_OPTION) {
                        direccion.delete();
                        JOptionPane.showMessageDialog(null, "Registro Eliminado");
                    }
                    
                    if (opc == JOptionPane.NO_OPTION) {
                        
                    }
                } catch (Exception e) {
                }
            } else {
                JOptionPane.showMessageDialog(null, "El codigo del caso no se encuentra registrado.");
            }
        }
    }
}
