/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.File;
import javax.swing.JFileChooser;


/**
 *
 * @author Lenovo
 */
public class Menu_GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu_GUIPrincipal() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonIngresarDatos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonIngresarDatosDetective = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonIngresarDatosSospechoso = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonAbrirDatos = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelIconobasura = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Ingresar Datos del Caso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 20));

        jButtonIngresarDatos.setBackground(new java.awt.Color(248, 6, 204));
        jButtonIngresarDatos.setText("Ingresar Datos");
        jButtonIngresarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Ingresar Datos de Detective");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 180, -1));

        jButtonIngresarDatosDetective.setBackground(new java.awt.Color(248, 6, 204));
        jButtonIngresarDatosDetective.setText("Ingresar Datos");
        jButtonIngresarDatosDetective.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarDatosDetectiveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresarDatosDetective, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 156, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Ingresar Datos de Sospechoso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jButtonIngresarDatosSospechoso.setBackground(new java.awt.Color(248, 6, 204));
        jButtonIngresarDatosSospechoso.setText("Ingresar Datos");
        jButtonIngresarDatosSospechoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarDatosSospechosoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresarDatosSospechoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 156, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Ver Datos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        jButtonAbrirDatos.setBackground(new java.awt.Color(248, 6, 204));
        jButtonAbrirDatos.setText("Abrir Datos");
        jButtonAbrirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirDatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAbrirDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(153, 0, 153));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 87, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setText("Menu");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 70, 40));

        jLabelIconobasura.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Casos2Modi\\src\\Imagen Proyecto\\cerrar-sesion.png")); // NOI18N
        getContentPane().add(jLabelIconobasura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 50, 60));

        jButton1.setBackground(new java.awt.Color(248, 6, 204));
        jButton1.setText("Ingresar Anotacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 140, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Ingresar Anotacion del Caso");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Casos2Modi\\src\\Imagen Proyecto\\peakpx.jpg")); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarDatosActionPerformed
        Formulario f1 = new Formulario();
        f1.setVisible(true);
    }//GEN-LAST:event_jButtonIngresarDatosActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAbrirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirDatosActionPerformed
        VerDatos Vd = new VerDatos();
        Vd.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirDatosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegistroAnotaciones RA = new RegistroAnotaciones();
        RA.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonIngresarDatosDetectiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarDatosDetectiveActionPerformed
        DatosDtective Dt = new  DatosDtective();
        Dt.setVisible(true);
    }//GEN-LAST:event_jButtonIngresarDatosDetectiveActionPerformed

    private void jButtonIngresarDatosSospechosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarDatosSospechosoActionPerformed
        GuiRegistroSospechoso GS = new GuiRegistroSospechoso();
        GS.setVisible(true);
    }//GEN-LAST:event_jButtonIngresarDatosSospechosoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAbrirDatos;
    private javax.swing.JButton jButtonIngresarDatos;
    private javax.swing.JButton jButtonIngresarDatosDetective;
    private javax.swing.JButton jButtonIngresarDatosSospechoso;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIconobasura;
    // End of variables declaration//GEN-END:variables
}
